Fix some missed refactorings associated with move to Koin
I managed to miss these, including the whole of the androidTest
folder, which is a little worrying.

Nevertheless, the android tests pass on my device.

I have been unable to test the generate-quest-list.main.kts change
as I get the following error locally:
```
error: backend Internal error: Exception during IR lowering
The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50) (generate-quest-list.main.kts): org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
```

However it has run within GitHub actions on my fork, which suggests it works.