Grill fuel quest -- add OtherAnswer that this is just a firering, not a Grill (#5371)
* add a "not a BBQ" other answer

* try to fix compile issues

* cleanups

* try to fix compile error

* try NOT_BBQ as an enum

* enum kludge

* include

* try to get it to compile

* try to import variables

* try to get rid of "sealed interface class" in order to get it to compile

* add confirmNotBbq()

* add missing import

* indicate magic value

* try to get "sealed interface BbqFuelAnswer" to work

* try buttonPanelAnswers from dier_type

* try building_entrance items override

* whitespace cleanups

* Update app/src/main/java/de/westnordost/streetcomplete/quests/bbq_fuel/AddBbqFuelForm.kt

* rename NOT_BBQ => IsFirePitAnswer

* indicate what it is instead of what it is not, try different words for clarification and shortening

* rephrase other answer, use different message format

* try to fix compilation error
Failed to flatten XML for resource 'quest_bbq_fuel_not_a_bbq' with error: Invalid unicode escape sequence in string

* cleanup texts

* Update app/src/main/res/values/strings.xml

Co-authored-by: Flo Edelmann <florian-edelmann@online.de>

---------

Co-authored-by: Tobias Zwick <newton@westnordost.de>
Co-authored-by: Flo Edelmann <florian-edelmann@online.de>