possibly fix an NPE
(got this stacktrace:

java.lang.IllegalStateException: Fragment AddOpeningHoursForm{1114f3a} did not return a View from onCreateView() or this was called before onCreateView().
	at androidx.fragment.app.Fragment.requireView(Fragment.java:1964)
	at de.westnordost.streetcomplete.ktx.FragmentViewBindingPropertyDelegate.getValue(ViewBinder.kt:83)
	at de.westnordost.streetcomplete.quests.AbstractQuestFormAnswerFragment.getBinding(AbstractQuestFormAnswerFragment.kt:17)
	at de.westnordost.streetcomplete.quests.AbstractQuestFormAnswerFragment.checkIsFormComplete(AbstractQuestFormAnswerFragment.kt:32)
	at de.westnordost.streetcomplete.quests.opening_hours.AddOpeningHoursForm.access$checkIsFormComplete(AddOpeningHoursForm.kt:26)
	at de.westnordost.streetcomplete.quests.opening_hours.AddOpeningHoursForm$onCreate$1.invoke(AddOpeningHoursForm.kt:58)
	at de.westnordost.streetcomplete.quests.opening_hours.AddOpeningHoursForm$onCreate$1.invoke(AddOpeningHoursForm.kt:58)
	at de.westnordost.streetcomplete.util.AdapterDataChangedWatcher.onItemRangeInserted(AdapterDataChangedWatcher.kt:8)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:12684)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemInserted(RecyclerView.java:7689)
	at de.westnordost.streetcomplete.quests.opening_hours.adapter.RegularOpeningHoursAdapter.addWeekdays(RegularOpeningHoursAdapter.kt:154)
)